// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzqkytriimmwfsnjirwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6cWt5dHJpaW1td2ZzbmppcndmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNzQ3NjQsImV4cCI6MjA2MTg1MDc2NH0.yu8i0r2FvzxEX9-TZu_9Xai7aCwQ14pqQUkoqUIPWPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);